"""core functionality completed

Revision ID: 1de89fab4508
Revises: d9b5024175fb
Create Date: 2026-04-01 21:11:28.156272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de89fab4508'
down_revision: Union[str, Sequence[str], None] = 'd9b5024175fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('duration_played_seconds', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('taste_vector', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_genres', sa.JSON(), nullable=True),
    sa.Column('preferred_decades', sa.JSON(), nullable=True),
    sa.Column('mood_preferences', sa.JSON(), nullable=True),
    sa.Column('explicit_content_filter', sa.Boolean(), nullable=True),
    sa.Column('recommendation_diversity', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('is_disliked', sa.Boolean(), nullable=True),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_user_ratings_user_track')
    )
    op.create_table('session_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_events')
    op.drop_table('user_ratings')
    op.drop_table('user_preferences')
    op.drop_table('sessions')
    op.drop_table('listening_history')
    # ### end Alembic commands ###
